# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8zner < Formula
  desc "Production-ready Kubernetes clusters on Hetzner Cloud using Talos Linux"
  homepage "https://github.com/imamik/k8zner"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imamik/k8zner/releases/download/v0.1.0/k8zner_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "c912f0a28d6b551c8b8d69be3d4f31aeb07ea59b82588e8065f6ced33a4b4939"

      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imamik/k8zner/releases/download/v0.1.0/k8zner_0.1.0_Darwin_arm64.tar.gz"
      sha256 "182fa72b369748d39471b8fa489e17a848b317621a448b843b2918930a32e9b1"

      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/imamik/k8zner/releases/download/v0.1.0/k8zner_0.1.0_Linux_x86_64.tar.gz"
      sha256 "c93ead01f73ff1416f015f686484c80c090959ea9260c651f8b68ac44dba87e3"
      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imamik/k8zner/releases/download/v0.1.0/k8zner_0.1.0_Linux_arm64.tar.gz"
      sha256 "74d0218c5f4fa62c7a74e31e1cceb5134ccc6b08799e580812318a51e89cafed"
      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
  end

  test do
    system "#{bin}/k8zner", "version"
  end
end
