# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8zner < Formula
  desc "Production-ready Kubernetes clusters on Hetzner Cloud using Talos Linux"
  homepage "https://github.com/imamik/k8zner"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imamik/k8zner/releases/download/v0.5.0/k8zner_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "4e6abdde82c873d4361748f88e309260b86fad839a442a20d75d425ed123a17f"

      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imamik/k8zner/releases/download/v0.5.0/k8zner_0.5.0_Darwin_arm64.tar.gz"
      sha256 "8bff5b0b1b16230be3fccd69250660d9ebfcf743003cc0ec52fb720ff88d1e68"

      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/imamik/k8zner/releases/download/v0.5.0/k8zner_0.5.0_Linux_x86_64.tar.gz"
      sha256 "124c5cd790616efd063f77ef442f3cc7bf7f8640267d7959025b9fc97beb451f"
      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imamik/k8zner/releases/download/v0.5.0/k8zner_0.5.0_Linux_arm64.tar.gz"
      sha256 "7d2d7d00d2cea414a6da30ad91507800da49f56d64eae43682aff4a97e4a9193"
      def install
        bin.install "k8zner"

        # Install shell completions
        generate_completions_from_executable(bin/"k8zner", "completion")
      end
    end
  end

  test do
    system "#{bin}/k8zner", "version"
  end
end
